name: Test find_lowest_number.py

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Compare outputs
      
    - name: Run test1
      run: python find_lowest_number.py test_data/test1_input.txt test_data/output1.txt
      
    - name: Compare test1 output
      run: diff test_data/output1.txt test_data/test1_expected.txt
      
    - name: Run test2
      run: python find_lowest_number.py test_data/test2_input.txt test_data/output2.txt

    - name: Compare test2 output
      run: diff test_data/output2.txt test_data/test2_expected.txt

    - name: Run test3
      run: python find_lowest_number.py test_data/test3_input.txt test_data/output3.txt
      
    - name: Compare test3 output
      run: diff test_data/output3.txt test_data/test3_expected.txt
